export const EXCEPTION = 'EXCEPTION';
export const CLEAR_EXCEPTION_MSG = 'CLEAR_EXCEPTION_MSG';

export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER";

export const GRAPHCOOL_AUTH_TOKEN_OBTAINED = "GRAPHCOOL_AUTH_TOKEN_OBTAINED";
export const GRAPHCOOL_AUTH_TOKEN_ERROR = "GRAPHCOOL_AUTH_TOKEN_ERROR";
export const GRAPHCOOL_AUTH_TOKEN_CLEAR = "GRAPHCOOL_AUTH_TOKEN_CLEAR";

export const SET_USER_ID = "SET_USER_ID";
export const CLEAR_USER_ID = "CLEAR_USER_ID";

export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
export const USER_DETAILS_LOADED = "USER_DETAILS_LOADED";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";
export const CLEAR_USER_DETAILS = "CLEAR_USER_DETAILS";

export const ADD_FAMILY_LOADING = "ADD_FAMILY_LOADING";
export const ADD_FAMILY_LOADED = "ADD_FAMILY_LOADED";
export const ADD_FAMILY_ERROR = "ADD_FAMILY_ERROR";
export const CLEAR_ADD_FAMILY = "CLEAR_ADD_FAMILY";

export const GET_FAMILY_LOADING = "GET_FAMILY_LOADING";
export const GET_FAMILY_LOADED = "GET_FAMILY_LOADED";
export const GET_FAMILY_ERROR = "GET_FAMILY_ERROR";
export const CLEAR_GET_FAMILY = "CLEAR_GET_FAMILY";

export const SAVE_PRESCP_LOADING = "SAVE_PRESCP_LOADING";
export const SAVE_PRESCP_LOADED = "SAVE_PRESCP_LOADED";
export const SAVE_PRESCP_ERROR = "SAVE_PRESCP_ERROR";
export const CLEAR_PRESCP = "CLEAR_PRESCP";

export const SET_PROFILE_URL = "SET_PROFILE_URL";
export const CLEAR_PROFILE_URL = "CLEAR_PROFILE_URL";
export const UPLOADING_PROFILE_PIC = "UPLOADING_PROFILE_PIC";
export const UPLOADED_PROFILE_PIC = "UPLOADED_PROFILE_PIC";
export const ERROR_UPLOADING_PROFILE_PIC = "ERROR_UPLOADING_PROFILE_PIC";

export const SET_ADD_MEM_IMG_URL = "SET_ADD_MEM_IMG_URL";
export const CLEAR_ADD_MEM_IMG_URL = "CLEAR_ADD_MEM_IMG_URL";
export const UPLOADING_ADD_MEM_IMG_PIC = "UPLOADING_ADD_MEM_IMG_PIC";
export const UPLOADED_ADD_MEM_IMG_PIC = "UPLOADED_ADD_MEM_IMG_PIC";
export const ERROR_UPLOADING_ADD_MEM_IMG_PIC = "ERROR_UPLOADING_ADD_MEM_IMG_PIC";

export const UPLOADING_ADD_MEM = "UPLOADING_ADD_MEM";
export const UPLOADED_ADD_MEM = "UPLOADED_ADD_MEM";
export const ERROR_ADD_MEM = "ERROR_ADD_MEM";
export const CLEAR_ADD_MEM = "ERROR_ADD_MEM";

export const SET_FAMILY_IMG_URL = "SET_FAMILY_IMG_URL";
export const CLEAR_FAMILY_IMG_URL = "CLEAR_FAMILY_IMG_URL";
export const UPLOADING_FAMILY_IMG_PIC = "UPLOADING_FAMILY_IMG_PIC";
export const UPLOADED_FAMILY_IMG_PIC = "UPLOADED_FAMILY_IMG_PIC";
export const ERROR_UPLOADING_FAMILY_IMG_PIC = "ERROR_UPLOADING_FAMILY_IMG_PIC";

export const SET_PRESCRIPTION_URL = "SET_PRESCRIPTION_URL";
export const CLEAR_PRESCRIPTION_URL = "CLEAR_PRESCRIPTION_URL";
export const UPLOADING_PRESCRIPTION = "UPLOADING_PRESCRIPTION_IMAGE";
export const UPLOADED_PRESCRIPTION = "UPLOADED_PRESCRIPTION_IMAGE";
export const ERROR_UPLOADING_PRESCRIPTION = "ERROR_UPLOADING_PRESCRIPTION";
// export const CLEAR_PRESCRIPTION_STATUS = "CLEAR_PRESCRIPTION_STATUS";

export const SET_PRESCRIPTION_LIST = "SET_PRESCRIPTION_LIST";
export const CLEAR_PRESCRIPTION_LIST = "CLEAR_PRESCRIPTION_LIST";
export const PRESCRIPTION_LIST_LOADING = "PRESCRIPTION_LIST_LOADING";
export const PRESCRIPTION_LIST_LOADED = "PRESCRIPTION_LIST_LOADED";
export const PRESCRIPTION_LIST_ERROR = "PRESCRIPTION_LIST_ERROR";