# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FamilyTree' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FamilyTree
    pod 'Firebase/Core'
    pod 'Firebase/Auth'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'FamilyTreeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
  end

end
